### ISSUE TITLE
Widescreen in voiceonly patches - what is the point?

### ISSUE THREAD

**Issue by marakeusz** [07th-mod/guide#1]
Like in topic. Voice-only patche contain the init.txt file which is changing resolution to widescreen. It results with text appearing on the black bars. Of course it is hardly the problem. I can imagine people may prefer it that way. I am just wondering if it was intentionally. Personally I just removed that file.

**Comment by ItaloKnox** [comment]
Oops, my bad. I completely forgot about that, going to update it right now. Thanks for letting me know.

**Comment by ItaloKnox** [comment]
Oh, by the way, I thinking you're talking about Himatsubushi. Is that right?

**Comment by marakeusz** [comment]
ep 2 also is having widescreen init. I am speaking about patches downloaded via https://github.com/07th-mod/guide/wiki/Part-1.1:-Voices-only-Patch

**Comment by ItaloKnox** [comment]
Just asked because I had this mistake with Himatsu. Watanagashi should be like that since the patch isn't exactly an official release, just an early version of the patch.
