### ISSUE TITLE
hi i have a mac and i have some problems installing the patch

### ISSUE THREAD

**Issue by erst0913** [07th-mod/guide#11]
when i instal just like the guide says and open the game the backgrounds and the screen moves (instead of seeing the new resolution i see everything in the old resolution and the screen gets cut in half), also i can't seem to get the voices to work, the best i could get was the ps3 sprites with everything else from the steam version. also it would help if you explain how to change the binary on mac. i also tried the script advanced installation but i just couldn't find the 7zip that works with mac. I am not that good when it comes to gaming on a computer so if you could explain things with a little more details would help those of us that know little too nothing about installing files and that type of stuff.

**Comment by ItaloKnox** [comment]
It's hard to help because you created an issue in the wrong place. Which game exactly are you trying to install the patch? Is it Umineko?

**Comment by erst0913** [comment]
sorry, yes Umineko.

**Comment by ItaloKnox** [comment]
Ok, I can more or less get the gist of it now. Let's forget the installation script, this will take a lot of time and won't be worth it.

To make things faster, please post a screenshot of the game folder with the patch installed next time you reply here. That will help a lot.


Now, I have a few things I need to know:

Did you download the file ``umineko4_FOR_MAC_USERS``? You should rename it to ``umineko4`` and put it on ``Umineko\Umineko1to4.app\Contents\MacOS\``. Inside this folder, there is a file with the same name, allow the system to overwrite it.

Also, did you download the file ``0.utf`` and put it at ``Umineko\``? The should be a file with the same name there, allow the system to overwrite it.

If you didn't download the two files I said above, here are the links:
[umineko4_FOR_MAC_USERS](https://github.com/07th-mod/umineko-question/releases/download/v2.9.0/umineko4_FOR_MAC_USERS)
[0.utf](https://github.com/07th-mod/umineko-question/releases/download/v2.9.5/0.utf)

To help you compare between your folder and mine, here is a screenshot of my installation. Your folder should look like this:
![firefox_2017-12-02_14-18-01](https://user-images.githubusercontent.com/4702556/33517454-a324b920-d76b-11e7-8080-bd07cb379b56.png)

**Comment by erst0913** [comment]
<img width="1279" alt="captura de pantalla 2017-12-03 a la s 2 59 11 p m" src="https://user-images.githubusercontent.com/34149745/33529168-bb3037d6-d83a-11e7-8faa-8e7c369ff58e.png">
<img width="1081" alt="captura de pantalla 2017-12-03 a la s 2 59 50 p m" src="https://user-images.githubusercontent.com/34149745/33529172-c437f580-d83a-11e7-90aa-c6371696d2f0.png">
<img width="1077" alt="captura de pantalla 2017-12-03 a la s 3 00 02 p m" src="https://user-images.githubusercontent.com/34149745/33529173-c7c49adc-d83a-11e7-9c65-e71abd3c827b.png">

**Comment by erst0913** [comment]
i just added the voices and it looks like this, i am not sure if they are supposed to look like this.
<img width="1080" alt="captura de pantalla 2017-12-03 a la s 3 04 40 p m" src="https://user-images.githubusercontent.com/34149745/33529207-721aa742-d83b-11e7-91a9-9be75abf3f92.png">
<img width="613" alt="captura de pantalla 2017-12-03 a la s 3 04 53 p m" src="https://user-images.githubusercontent.com/34149745/33529208-741d1b92-d83b-11e7-99c6-d8fb7ad0c4f3.png">
<img width="1010" alt="captura de pantalla 2017-12-03 a la s 3 05 02 p m" src="https://user-images.githubusercontent.com/34149745/33529209-75db77bc-d83b-11e7-86cd-e60ef1fcba4a.png">

**Comment by erst0913** [comment]
i also downloaded a file that says widescreen and i put it with the other files but it didn't help
<img width="561" alt="captura de pantalla 2017-12-03 a la s 3 06 32 p m" src="https://user-images.githubusercontent.com/34149745/33529219-b3ae5b72-d83b-11e7-9909-20a987db5b30.png">
<img width="582" alt="captura de pantalla 2017-12-03 a la s 3 06 43 p m" src="https://user-images.githubusercontent.com/34149745/33529221-b52d02aa-d83b-11e7-8b1d-48fd8aa2467e.png">

**Comment by ItaloKnox** [comment]
First, delete the file ``0.utf`` and ``umineko4`` in your game folder. Ten [download this file](https://transfer.sh/VYPMr/patch.zip) and extract it into your game folder. If it asks you to overwrite any files, accept. If it doesn't, no problem.

After that run the ``umineko4`` file in ``Umineko\Umineko1to4.app\Contents\MacOS\``. It should fix the issue.

**Comment by erst0913** [comment]
how i run the umineko4 file in Umineko\Umineko1to4.app\Contents\MacOS\? 
i tried doing everything else and trying to open the game but it wouldn't open. 
<img width="449" alt="captura de pantalla 2017-12-03 a la s 3 52 57 p m" src="https://user-images.githubusercontent.com/34149745/33529683-3c8309a6-d842-11e7-84a6-afc1d96068c3.png">
<img width="965" alt="captura de pantalla 2017-12-03 a la s 3 53 05 p m" src="https://user-images.githubusercontent.com/34149745/33529684-3e46e83e-d842-11e7-822b-0c8f62cd8530.png">
i copied everything that was in the patch file to the umineko folder.

**Comment by erst0913** [comment]
<img width="766" alt="captura de pantalla 2017-12-03 a la s 4 08 09 p m" src="https://user-images.githubusercontent.com/34149745/33529846-3cac48f0-d844-11e7-95fc-3461789ad15d.png">
<img width="767" alt="captura de pantalla 2017-12-03 a la s 4 08 18 p m" src="https://user-images.githubusercontent.com/34149745/33529847-3cffbce2-d844-11e7-9a17-6e028abb8b27.png">
 
is it here that i have to run umineko4?

**Comment by ItaloKnox** [comment]
You have to run the file ``umineko4`` that is inside ``Umineko\Umineko1to4.app\Contents\MacOS``. It's not that hard to understand.

The file you are trying to open (``Umineko1to4.exe``) is for Windows.

**Comment by ItaloKnox** [comment]
I can see it's a Steam folder so after extracting the file I sent all you have to do is open the game on Steam, then.

**Comment by erst0913** [comment]
<img width="48" alt="captura de pantalla 2017-12-03 a la s 4 27 06 p m" src="https://user-images.githubusercontent.com/34149745/33529998-d3d77a22-d846-11e7-8bea-046b357b1df8.png">
i tried opening it an it know appears like that.

**Comment by erst0913** [comment]
i used left click on the app and than pressed show content 
<img width="751" alt="captura de pantalla 2017-12-03 a la s 4 29 32 p m" src="https://user-images.githubusercontent.com/34149745/33530027-3e4169e0-d847-11e7-98a7-5a7724da1a63.png">
then i clicked mac os
<img width="751" alt="captura de pantalla 2017-12-03 a la s 4 29 32 p m" src="https://user-images.githubusercontent.com/34149745/33530029-473c0f50-d847-11e7-9e67-fa4766c0d0af.png">

but it only shows this
<img width="764" alt="captura de pantalla 2017-12-03 a la s 4 28 30 p m" src="https://user-images.githubusercontent.com/34149745/33530033-4e45b03a-d847-11e7-8676-2d09c1085a25.png">
is this what you mean with inside Umineko\Umineko1to4.app\Contents\MacOS.

**Comment by erst0913** [comment]
the game opened but it looks like this
<img width="950" alt="captura de pantalla 2017-12-03 a la s 4 32 18 p m" src="https://user-images.githubusercontent.com/34149745/33530046-97fae510-d847-11e7-9463-5a46ef67347f.png">

**Comment by erst0913** [comment]
i think i found the file you talked about but i i tried opening that one and nothing changed the game looked the same like in the screenshots i send you.
<img width="1160" alt="captura de pantalla 2017-12-03 a la s 4 38 42 p m" src="https://user-images.githubusercontent.com/34149745/33530124-7dadf80e-d848-11e7-9a22-ee3880f52827.png">

**Comment by ItaloKnox** [comment]
Yes, that's the file. Did you open the game using Steam?

**Comment by erst0913** [comment]
yes i did open it using steam, this is how it looks:
<img width="1037" alt="captura de pantalla 2017-12-03 a la s 4 44 38 p m" src="https://user-images.githubusercontent.com/34149745/33530160-4742d9a0-d849-11e7-8eb0-511f051f951d.png">

**Comment by ItaloKnox** [comment]
I have no idea where the issue is, maybe we're having a communication issue.
I suggest trying to reinstall the game and the patch from scratch.

**Comment by erst0913** [comment]
i just realized i didn't replace the umineko 4 for the umineko 4 for mac users and renamed it umineko, now i did it and this happened.
<img width="1155" alt="captura de pantalla 2017-12-03 a la s 4 56 46 p m" src="https://user-images.githubusercontent.com/34149745/33530273-29d69346-d84b-11e7-87fe-c6221192c2ed.png">
when i open it from the umineko4
<img width="1280" alt="captura de pantalla 2017-12-03 a la s 4 56 55 p m" src="https://user-images.githubusercontent.com/34149745/33530275-366374d0-d84b-11e7-891d-02f7016879de.png">
when i try to open it from steam
<img width="668" alt="captura de pantalla 2017-12-03 a la s 4 57 06 p m" src="https://user-images.githubusercontent.com/34149745/33530280-4955f144-d84b-11e7-88d7-514bbcea82ed.png">

**Comment by ItaloKnox** [comment]
I will ping @drojf to take a look at this. He might be able to figure out if the executable is broken or not.

**Comment by erst0913** [comment]
thanks, i dont know what else to do i followed every step you gave me.

**Comment by drojf** [comment]
Can you try the instructions here?: https://github.com/07th-mod/umineko-question/issues/56#issuecomment-284396896

Maybe we should make this the default method for mac installations...

**Comment by erst0913** [comment]
@drojf 
<img width="1280" alt="captura de pantalla 2017-12-09 a la s 3 11 39 p m" src="https://user-images.githubusercontent.com/34149745/33799131-599b171c-dcf3-11e7-8aa2-dcd2146dc0fc.png">

that helped me but i still can't hear the voices or see the backgrounds. I dont mind the voices much but i really would like to play with the ps3 backgrounds.
<img width="928" alt="captura de pantalla 2017-12-09 a la s 3 13 51 p m" src="https://user-images.githubusercontent.com/34149745/33799149-a03bdc1a-dcf3-11e7-8cc5-874e8cd4e3f1.png">
<img width="931" alt="captura de pantalla 2017-12-09 a la s 3 14 02 p m" src="https://user-images.githubusercontent.com/34149745/33799152-a20ab458-dcf3-11e7-9d68-5f063a9680ef.png">

**Comment by erst0913** [comment]
<img width="1280" alt="captura de pantalla 2017-12-09 a la s 3 19 33 p m" src="https://user-images.githubusercontent.com/34149745/33799175-6569562a-dcf4-11e7-9d7e-79cf0a61bbbe.png">
man it finally worked i just had to download the 0.utf again and apply it to the patch you send me. Thanks a lot bro, also will you do the same patch you just did for mac users when the answers arcs are finished so those of us that can't play without it can?

**Comment by ItaloKnox** [comment]
That's good, sorry it took so long. I'll make this the default installation method so people using Mac won't have the same issue again. I'll also tell the team to prepare the same thing for the answer arcs, don't worry.
