### ISSUE TITLE
Blackscreen after Patch Watanagashi

### ISSUE THREAD

**Issue by zeromic** [07th-mod/guide#12]
After i installed Watanagashi.PS3.Voice.and.Graphics.Installer.exe the game starts with a black screen and sound. Only the "Quit" Dialog box is visible.

Edit: Reinstall and Executing the Patch again as Admin did not help

**Comment by P-Chang** [comment]
Sorry, we need more information.

1.OS
2.Store that you use in buy it.
3.Product that you bought(Steam, MG standalone, MG Bundle).

And upload output_log.txt that is in
Steam\steamapps\common\Higurashi 02 - Watanagashi\HigurashiEp02_Data

I'm not native English speaker, sorry for my broken English.

**Comment by zeromic** [comment]
1. Windows 10
2. Humble Bundles Mangagamer Bundle
3. Steam
4. Tried it first time with Ark 2(Watanagashi) so i dont know

output_log of the blackscreen version:
[output_log.txt](https://github.com/07th-mod/guide/files/1568725/output_log.txt)


I did the manual installatio and everything works now.

**Comment by ItaloKnox** [comment]
Looks like you were missing a bunch of stuff in the CG folder.

If you used the installer, there's a chance the download didn't finish properly (got that recently, github times out the download if you can't download it fast enough - not really our fault in this case).

Anyway, glad you managed to get it working without our help. Reopen this issue if you need anything else.
