### ISSUE TITLE
What programming language and environment did you used for making the installer patch GUI ?

### ISSUE THREAD

**Issue by gagantous** [07th-mod/guide#13]
I am just curious, how do you make that ?

**Comment by ItaloKnox** [comment]
Hi,

The GUI was made in [Advanced Installer](https://www.advancedinstaller.com/) and the internal code (that actually install the patch) is made in Windows batch.

**Comment by gagantous** [comment]
@ItaloKnox Are you using premium app for Advanced Installer ? or the trial version ?

**Comment by ItaloKnox** [comment]
I did some work that required the Architect edition so I have it, but you should be able to replicate the same installer in any edition since it doesn't use any advanced features (the advanced steps are done outside the installer).

**Comment by gagantous** [comment]
How could you bought the app for $400 ? Did you saving some money ? @ItaloKnox

**Comment by ItaloKnox** [comment]
lol, of course not. The license is actually from a company I used to do some work from outside. I still have the license until they decide to revoke it. 😆

**Comment by gagantous** [comment]
ohhh okay thanks for the explanation @ItaloKnox
