### ISSUE TITLE
Installer detect as a virus from avast antivirus

### ISSUE THREAD

**Issue by gagantous** [07th-mod/guide#14]
I tried to install part 2,3,4 using wndows installer but it was detected as virus like alert below
is this a virus ? or a false positive ? 

i have make sure that the installer is from github and not from any other website, so there is no doubt about the file being hijacked by someone

![16](https://user-images.githubusercontent.com/24579576/34429977-66aaf7ea-ec9a-11e7-8f51-d4d84bd2046e.JPG)

**Comment by ItaloKnox** [comment]
According to the wiki:

> PSA: as reported, some antivirus softwares might warn you about the installer. This is a false positive, and it happens because the installer runs a batch file (that results in the CMD window opening to download and install the patch). The installer code can be freely accessed in our Resource repository and is clean of viruses.

**Comment by gagantous** [comment]
Okay thanks (y)
