### ISSUE TITLE
Error explanation in installer patch

### ISSUE THREAD

**Issue by gagantous** [07th-mod/guide#15]
i know that there is a note said `If you get an error, this is completely normal`

but why this error keep appear ? what's the meaning of this 

```
12/29 16:38:35 [ERROR] WinTLS: Failed to encrypt a message! Error: The specified data could not be encrypted.
(80090329)

12/29 16:38:35 [ERROR] WinTLS: Failed to encrypt a message! Error: The specified data could not be encrypted.
(80090329)

12/29 16:38:35 [ERROR] WinTLS: Failed to encrypt a message! Error: The specified data could not be encrypted.
(80090329)
```

what's this error about ?

**Comment by ItaloKnox** [comment]
That seems related to ``aria2c``, the program used to download the patch files. When does it appear? What happens afterward? Does it prevent you from installing the patch?

It would also be helpful if you created the issue in the right repository and provided more information, [as noted in the guide itself](https://github.com/07th-mod/guide/wiki/Support).
