### ISSUE TITLE
Loading previous save files before the installation patch;

### ISSUE THREAD

**Issue by Geno101** [07th-mod/guide#16]
This may or may not been covered or assumed from what has been mentioned in the manual load but I'm just wondering: 

After I installed the patch- the game loads up fine, however when I go to load a save file it will only load the background, without any sprites. I tried hitting new game that seems to work.  So my question for this is- does this need a manual install fix or do I just have to play the game from the beginning of the relevant chapter?

**Comment by ItaloKnox** [comment]
I don't know which game you are talking about but for Higurashi your saves won't work after you install the patch (you have to remove the patch to use them) and for Umineko the game doesn't behave correctly when you install or update the patch, but it depends on where the save was created and where the update changes the script.

Next time please open the issue in the right repository, this repository is not meant for issues related to the games, but only for the guide itself.
