### ISSUE TITLE
PS3 Backgrounds + Steam Sprites Unofficial Fork

### ISSUE THREAD

**Issue by jwgrlrrajn** [07th-mod/guide#2]
Hi, I just wanted to let you guys know that I went ahead and made graphics patches for Episodes 1-2 to go along with my unofficial fork of Tatarigoroshi. In doing that though, I changed github repositories so the address wouldn't be Tatarigoroshi specific anymore.

If you could please add the new [Steam sprites + PS3 backgrounds patch](https://github.com/jwgrlrrajn/higurashi-steam-sprite-mods/releases) to the Unofficial Forks section of Getting Started, I'll be able to delete the old repo and free up some space.

**Comment by ItaloKnox** [comment]
Thanks for the heads up, it should be properly fixed now. I'm planning to give it a proper page, but it's a matter for when the next chapter is released, for now I'll skip any more work and complain about my team on Overwatch. Anyway, thanks!

**Comment by ItaloKnox** [comment]
Oh, by the way, the 1gb limit as far as I know is only for the whole repository. The files uploaded in a release shouldn't count towards this limit. You just have to drop a zip in the release (it should upload fine as long it is not more than 2gb/file).

**Comment by jwgrlrrajn** [comment]
Really? I'll have to check that out after I get home then. Thank you.

**Comment by jwgrlrrajn** [comment]
Looks like you were right. I was able to upload the release file with no problem. Thank you. I'll close this now, and I'll let you know if/when I get around to Himatsubishi.
