### ISSUE TITLE
Chiru voices link broken

### ISSUE THREAD

**Issue by ChipBrent** [07th-mod/guide#20]
Points to https://github.com/07th-mod/resources/releases/download/Bern/UminekoChiru-Voices.zip
Should be https://github.com/07th-mod/resources/releases/download/Bern/UminekoChiru-Voices.7z

In this section to be more specific https://github.com/07th-mod/guide/wiki/Umineko-Part-1---Voice-and-Graphics-Patch#manual-installation-windowsmac

**Comment by ItaloKnox** [comment]
Thanks, I changed builds today and forgot to fix the manual links. I just fixed it. 👍
