### ISSUE TITLE
Umineko Voices only Patch Broken Link

### ISSUE THREAD

**Issue by rasnauf** [07th-mod/guide#21]
The link to the Voices archive for Answer Arcs Ch.5~8 in the wiki is broken. Upon further inspection, https://github.com/07th-mod/resources/releases/download/Bern/UminekoChiru-Voices.zip does not work but https://github.com/07th-mod/resources/releases/download/Bern/UminekoChiru-Voices.7z does. The simplest solution is to amend the link in the wiki.

https://github.com/07th-mod/guide/wiki/Umineko-Part-1.1---Voices-only-Patch

**Comment by drojf** [comment]
Thanks, I've updated it just now.
