### ISSUE TITLE
Chapter 6?

### ISSUE THREAD

**Issue by BakaUshi** [07th-mod/guide#24]
Chapter 6 just released on MangaGamer's site and Steam - I would love to see the patch for this chapter.  Thanks!

**Comment by orian34** [comment]
It's already being worked on. Join the discord if you want to see it live.

Not sure about writing an issue for that 🤔

**Comment by enumag** [comment]
You can find the Discord [here](https://discord.gg/acSbBtD).

As for chapter 6, we're already working hard on it. Voice only patch is almost ready (see https://github.com/07th-mod/tsumihoroboshi). The PS3 Graphics patch will take about a month to complete.

Also we will have some new exciting features this time around that you can look forward to. Most notably LipSync and a PS3 opening but there is much more.
