### ISSUE TITLE
MOD Settings and Hotkeys displayed

### ISSUE THREAD

**Issue by Dalaios** [07th-mod/guide#25]
Hello,

I accidentally pressed some keys I guess and suddenly half of the screen is filled with some display of MOD Settings, Vanilla Hotkeys and MOD Hotkeys.

No matter what I press I am not able to make this display disappear again. I even reinstalled the game but it's still there.

I have a screenshot as well:

![meakashi screenshot](https://user-images.githubusercontent.com/40486871/41764939-dd31648e-7602-11e8-9a43-bf1adea760ff.jpg)

I would be very thankful if anyone could tell me how to make that disappear again. It's really impossible for me to continue playing like that.

Thank you in advance.

**Comment by orian34** [comment]
It's F10, works in game. You should ask that in the Discord, no need to make an issue for a question 👌 .

**Comment by enumag** [comment]
The F10 key doesn't work in the main menu, you need to start the game, then press F10 and it will go away.

**Comment by ItaloKnox** [comment]
Just in case you are curious, [this is the full list of shortcuts](https://github.com/07th-mod/guide/wiki/Higurashi-Part-2---Patch-configuration-and-keyboard-shortcuts). It's actually linked by the end of the installation tutorial. 👍

**Comment by Dalaios** [comment]
Thanks guys, I got really desperate when nothing worked. I would have never thought about starting the game to make it disappear. Thank you a lot for the fast help :)

**Comment by enumag** [comment]
@Dalaios Don't worry about it. Also we might be able to fix the issue later.
