### ISSUE TITLE
Mac/Linux UI Mod link for Higurashi Himatsubushi is broken

### ISSUE THREAD

**Issue by bl4ckout31** [07th-mod/guide#26]
The link for Mac/Linux UI Mod for Higurashi Himatsubushi ([https://07th-mod.com/rikachama/Himatsubushi-UI_UNIX.7z](https://07th-mod.com/rikachama/Himatsubushi-UI_UNIX.7z)) gives a 403 HTTP error.

**Comment by ItaloKnox** [comment]
My bad. I have the bad habit of using ``rsync -avP`` to sync new updates, this time it synced a file without proper permissions. I fixed the issue, thanks for letting me know!
