### ISSUE TITLE
Autopatcher looking for Patch v1.0 instead of newest

### ISSUE THREAD

**Issue by Asnanon** [07th-mod/guide#3]
While letting the new autopatcher run through today twice, I saw that the patcher downloads the newest patch, but it wants to install with the v1.0 patch version. Which leads to errors and a premature stopping of the patching process.

edit: I just saw that I posted it in the wrong repo, sorry about that. I'm talking about the meakashi autopatcher, although that might be a problem for the other releases as well if it's hardcoded.

**Comment by ItaloKnox** [comment]
You're correct, no problem about posting it in the wrong repo. Thanks a lot for the heads up, I just pushed a fix and it should try to extract the right file now.
